// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7tSQdxgu7FmCVtUmJP9sF2
// Component: IeOLwqhYeWPL

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NavBar from "../../NavBar"; // plasmic-import: pgplTJIampbm/component
import Nn from "../../Nn"; // plasmic-import: cTpe4fEaek5z/component
import { CategoryCollection } from "@plasmicpkgs/commerce";
import Collection from "../../Collection"; // plasmic-import: ZCdjyKIEJTaF/component
import { CategoryMedia } from "@plasmicpkgs/commerce";
import { CategoryField } from "@plasmicpkgs/commerce";
import { ProductCollection } from "@plasmicpkgs/commerce";
import ProductMain from "../../ProductMain"; // plasmic-import: KgwNR90if1Xd/component
import { DataFetcher } from "@plasmicpkgs/plasmic-query";
import ShopingSection from "../../ShopingSection"; // plasmic-import: HLScY8F9FLDn/component
import Instagram from "../../Instagram"; // plasmic-import: IX1Xf65O6Aw9/component
import Footer from "../../Footer"; // plasmic-import: qugGYwjKYlY4/component
import { ProductTextField } from "@plasmicpkgs/commerce";
import { ProductMedia } from "@plasmicpkgs/commerce";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 7tSQdxgu7FmCVtUmJP9sF2/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: IeOLwqhYeWPL/css

import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: pQhoyk-izhfk/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  heroSection?: Flex__<"div">;
  navBar?: Flex__<typeof NavBar>;
  container3?: Flex__<"div">;
  nn?: Flex__<typeof Nn>;
  h1?: Flex__<"h1">;
  button?: Flex__<"button">;
  h2?: Flex__<"h2">;
  columns?: Flex__<"div">;
  productMain?: Flex__<typeof ProductMain>;
  httpRestApiFetcher?: Flex__<typeof DataFetcher>;
  shopingSection?: Flex__<typeof ShopingSection>;
  instagram?: Flex__<typeof Instagram>;
  footer?: Flex__<typeof Footer>;
  productTextField?: Flex__<typeof ProductTextField>;
  productMedia?: Flex__<typeof ProductMedia>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"heroSection"}
            data-plasmic-override={overrides.heroSection}
            className={classNames(projectcss.all, sty.heroSection)}
          >
            <NavBar
              data-plasmic-name={"navBar"}
              data-plasmic-override={overrides.navBar}
              className={classNames("__wab_instance", sty.navBar)}
            />

            <section className={classNames(projectcss.all, sty.section__amioS)}>
              <Stack__
                as={"div"}
                data-plasmic-name={"container3"}
                data-plasmic-override={overrides.container3}
                hasGap={true}
                className={classNames(projectcss.all, sty.container3)}
              >
                <Nn
                  data-plasmic-name={"nn"}
                  data-plasmic-override={overrides.nn}
                  className={classNames("__wab_instance", sty.nn)}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__zbz9Q)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__eSRt)}
                  >
                    <h1
                      data-plasmic-name={"h1"}
                      data-plasmic-override={overrides.h1}
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1
                      )}
                    >
                      {"The care you've always needed"}
                    </h1>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__usw6G
                      )}
                    >
                      {"A RANGE OF PRODUCTS FOR YOU"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___7VFKr
                      )}
                    >
                      <button
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames(
                          projectcss.all,
                          projectcss.button,
                          projectcss.__wab_text,
                          sty.button
                        )}
                      >
                        {"Shop Now"}
                      </button>
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </section>
          </div>
          <section className={classNames(projectcss.all, sty.section__brygH)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__uGdi7)}
            >
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3__mIgZ
                )}
              >
                {
                  "MOISTURE IS THE ESSENCE OF WETNESS, AND WETNESS IS THE ESSENCE OF BEAUTY."
                }
              </h3>
              <Stack__
                as={PlasmicLink__}
                hasGap={true}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__j2Ndb
                )}
                component={Link}
                href={`/aboutus`}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__f4F7H
                  )}
                >
                  {"Find out more"}
                </div>
                <RightArrowIcon
                  className={classNames(projectcss.all, sty.svg__dzCsm)}
                  role={"img"}
                />
              </Stack__>
            </Stack__>
          </section>
          <Stack__
            as={"section"}
            hasGap={true}
            className={classNames(projectcss.all, sty.section__npjpl)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__uu3W)}
            >
              <h2
                data-plasmic-name={"h2"}
                data-plasmic-override={overrides.h2}
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2
                )}
              >
                {"Categories"}
              </h2>
            </Stack__>
            <div
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__uOt4S)}>
                <CategoryCollection
                  category={"6267de7030e3370018d347ab"}
                  className={classNames(
                    "__wab_instance",
                    sty.categoryCollection___7PwUk
                  )}
                  emptyMessage={
                    <DataCtxReader__>
                      {$ctx => (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fwBX
                          )}
                        >
                          {"No collection found!"}
                        </div>
                      )}
                    </DataCtxReader__>
                  }
                  loadingMessage={
                    <DataCtxReader__>
                      {$ctx => (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__v0EnD
                          )}
                        >
                          {"Loading..."}
                        </div>
                      )}
                    </DataCtxReader__>
                  }
                >
                  <DataCtxReader__>
                    {$ctx => (
                      <Collection
                        className={classNames(
                          "__wab_instance",
                          sty.collection__lh0Qh
                        )}
                      >
                        <CategoryMedia
                          className={classNames(
                            "__wab_instance",
                            sty.categoryMedia__fWuH2
                          )}
                        />
                      </Collection>
                    )}
                  </DataCtxReader__>
                </CategoryCollection>
              </div>
              <div className={classNames(projectcss.all, sty.column__jgDct)}>
                <CategoryCollection
                  category={"6267e0ec4443d3001919b87b"}
                  className={classNames(
                    "__wab_instance",
                    sty.categoryCollection__e57S2
                  )}
                  emptyMessage={
                    <DataCtxReader__>
                      {$ctx => (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__t3GP6
                          )}
                        >
                          {"No collection found!"}
                        </div>
                      )}
                    </DataCtxReader__>
                  }
                  loadingMessage={
                    <DataCtxReader__>
                      {$ctx => (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__aWuQr
                          )}
                        >
                          {"Loading..."}
                        </div>
                      )}
                    </DataCtxReader__>
                  }
                >
                  <DataCtxReader__>
                    {$ctx => (
                      <Collection
                        className={classNames(
                          "__wab_instance",
                          sty.collection__hjxQu
                        )}
                      >
                        <CategoryMedia
                          className={classNames(
                            "__wab_instance",
                            sty.categoryMedia__q9CGj
                          )}
                        />
                      </Collection>
                    )}
                  </DataCtxReader__>
                </CategoryCollection>
              </div>
              <div className={classNames(projectcss.all, sty.column__uBYpk)}>
                <CategoryCollection
                  category={"6267e10630e3370018d76b94"}
                  className={classNames(
                    "__wab_instance",
                    sty.categoryCollection__mX5
                  )}
                  emptyMessage={
                    <DataCtxReader__>
                      {$ctx => (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vujNc
                          )}
                        >
                          {"No collection found!"}
                        </div>
                      )}
                    </DataCtxReader__>
                  }
                  loadingMessage={
                    <DataCtxReader__>
                      {$ctx => (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__sFkwY
                          )}
                        >
                          {"Loading..."}
                        </div>
                      )}
                    </DataCtxReader__>
                  }
                >
                  <DataCtxReader__>
                    {$ctx => (
                      <Collection
                        className={classNames(
                          "__wab_instance",
                          sty.collection__foGxF
                        )}
                      >
                        <CategoryMedia
                          className={classNames(
                            "__wab_instance",
                            sty.categoryMedia__kJuls
                          )}
                        />
                      </Collection>
                    )}
                  </DataCtxReader__>
                </CategoryCollection>
              </div>
            </div>
          </Stack__>
          <Stack__
            as={"section"}
            hasGap={true}
            className={classNames(projectcss.all, sty.section__nurFi)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___5WTi)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xUpln
                )}
              >
                {"Introducing Our Latest Products"}
              </div>
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3___1Rv9T
                )}
              >
                {"Limited reservations on upcoming products and restocks."}
              </h3>
              <Stack__
                as={PlasmicLink__}
                hasGap={true}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__fFo9X
                )}
                component={Link}
                href={`/item`}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__agn5N
                  )}
                >
                  {"See more product"}
                </div>
                <RightArrowIcon
                  className={classNames(projectcss.all, sty.svg__wvPuf)}
                  role={"img"}
                />
              </Stack__>
            </Stack__>
            <ProductCollection
              className={classNames(
                "__wab_instance",
                sty.productCollection__ciYs3
              )}
              count={4}
              emptyMessage={
                <DataCtxReader__>
                  {$ctx => (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kzMnx
                      )}
                    >
                      {"No product found!"}
                    </div>
                  )}
                </DataCtxReader__>
              }
              loadingMessage={
                <DataCtxReader__>
                  {$ctx => (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oq4W1
                      )}
                    >
                      {"Loading..."}
                    </div>
                  )}
                </DataCtxReader__>
              }
              sort={"latest-desc"}
            >
              <DataCtxReader__>
                {$ctx => (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__k28S3)}
                  >
                    <ProductMain
                      data-plasmic-name={"productMain"}
                      data-plasmic-override={overrides.productMain}
                      className={classNames("__wab_instance", sty.productMain)}
                    />

                    <DataFetcher
                      data-plasmic-name={"httpRestApiFetcher"}
                      data-plasmic-override={overrides.httpRestApiFetcher}
                      className={classNames(
                        "__wab_instance",
                        sty.httpRestApiFetcher
                      )}
                      dataName={"fetchedData"}
                      errorDisplay={
                        <DataCtxReader__>
                          {$ctx => "Error fetching data"}
                        </DataCtxReader__>
                      }
                      errorName={"fetchError"}
                      headers={{
                        "Content-Type": "application/json",
                        Accept: "application/json"
                      }}
                      loadingDisplay={
                        <DataCtxReader__>
                          {$ctx => "Loading..."}
                        </DataCtxReader__>
                      }
                      method={"GET"}
                      noLayout={false}
                      url={"https://api.github.com/users/plasmicapp/repos"}
                    />
                  </div>
                )}
              </DataCtxReader__>
            </ProductCollection>
          </Stack__>
          <ShopingSection
            data-plasmic-name={"shopingSection"}
            data-plasmic-override={overrides.shopingSection}
            className={classNames("__wab_instance", sty.shopingSection)}
          />

          <Instagram
            data-plasmic-name={"instagram"}
            data-plasmic-override={overrides.instagram}
            className={classNames("__wab_instance", sty.instagram)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />

          <ProductCollection
            className={classNames(
              "__wab_instance",
              sty.productCollection___7VKT
            )}
            emptyMessage={
              <DataCtxReader__>
                {$ctx => (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6L2P8
                    )}
                  >
                    {"No product found!"}
                  </div>
                )}
              </DataCtxReader__>
            }
            loadingMessage={
              <DataCtxReader__>
                {$ctx => (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nsvId
                    )}
                  >
                    {"Loading..."}
                  </div>
                )}
              </DataCtxReader__>
            }
          >
            <DataCtxReader__>
              {$ctx => (
                <div
                  className={classNames(projectcss.all, sty.freeBox___6ZPjO)}
                >
                  <ProductTextField
                    data-plasmic-name={"productTextField"}
                    data-plasmic-override={overrides.productTextField}
                    className={classNames(
                      "__wab_instance",
                      sty.productTextField
                    )}
                    field={"name"}
                  />

                  <ProductMedia
                    data-plasmic-name={"productMedia"}
                    data-plasmic-override={overrides.productMedia}
                    className={classNames("__wab_instance", sty.productMedia)}
                  />
                </div>
              )}
            </DataCtxReader__>
          </ProductCollection>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "heroSection",
    "navBar",
    "container3",
    "nn",
    "h1",
    "button",
    "h2",
    "columns",
    "productMain",
    "httpRestApiFetcher",
    "shopingSection",
    "instagram",
    "footer",
    "productTextField",
    "productMedia"
  ],
  heroSection: ["heroSection", "navBar", "container3", "nn", "h1", "button"],
  navBar: ["navBar"],
  container3: ["container3", "nn", "h1", "button"],
  nn: ["nn"],
  h1: ["h1"],
  button: ["button"],
  h2: ["h2"],
  columns: ["columns"],
  productMain: ["productMain"],
  httpRestApiFetcher: ["httpRestApiFetcher"],
  shopingSection: ["shopingSection"],
  instagram: ["instagram"],
  footer: ["footer"],
  productTextField: ["productTextField"],
  productMedia: ["productMedia"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  heroSection: "div";
  navBar: typeof NavBar;
  container3: "div";
  nn: typeof Nn;
  h1: "h1";
  button: "button";
  h2: "h2";
  columns: "div";
  productMain: typeof ProductMain;
  httpRestApiFetcher: typeof DataFetcher;
  shopingSection: typeof ShopingSection;
  instagram: typeof Instagram;
  footer: typeof Footer;
  productTextField: typeof ProductTextField;
  productMedia: typeof ProductMedia;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    heroSection: makeNodeComponent("heroSection"),
    navBar: makeNodeComponent("navBar"),
    container3: makeNodeComponent("container3"),
    nn: makeNodeComponent("nn"),
    h1: makeNodeComponent("h1"),
    button: makeNodeComponent("button"),
    h2: makeNodeComponent("h2"),
    columns: makeNodeComponent("columns"),
    productMain: makeNodeComponent("productMain"),
    httpRestApiFetcher: makeNodeComponent("httpRestApiFetcher"),
    shopingSection: makeNodeComponent("shopingSection"),
    instagram: makeNodeComponent("instagram"),
    footer: makeNodeComponent("footer"),
    productTextField: makeNodeComponent("productTextField"),
    productMedia: makeNodeComponent("productMedia"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "ShoeShop",
      description:
        "Ad ullamcorper eros nibh pharetra vulputate imperdiet consectetur vestibulum at ac posuere volutpat maecenas gravida dictum suscipit habitasse class scelerisque fermentum blandit mi a.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
