// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7tSQdxgu7FmCVtUmJP9sF2

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { CommerceProviderComponent } from "@plasmicpkgs/commerce-shopify";
import { CommerceProviderComponent as CommerceProviderComponent2 } from "@plasmicpkgs/commerce-saleor";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  commerceProviderComponentProps?: Partial<
    Omit<React.ComponentProps<typeof CommerceProviderComponent>, "children">
  >;
  commerceProviderComponent2Props?: Partial<
    Omit<React.ComponentProps<typeof CommerceProviderComponent2>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const {
    children,
    commerceProviderComponentProps,
    commerceProviderComponent2Props
  } = props;

  return (
    <CommerceProviderComponent
      {...commerceProviderComponentProps}
      accessToken={
        commerceProviderComponentProps &&
        "accessToken" in commerceProviderComponentProps
          ? commerceProviderComponentProps.accessToken!
          : "ef7d41c7bf7e1c214074d0d3047bcd7b"
      }
      storeDomain={
        commerceProviderComponentProps &&
        "storeDomain" in commerceProviderComponentProps
          ? commerceProviderComponentProps.storeDomain!
          : "next-js-store.myshopify.com"
      }
    >
      <CommerceProviderComponent2
        {...commerceProviderComponentProps}
        saleorApiUrl={
          commerceProviderComponentProps &&
          "saleorApiUrl" in commerceProviderComponentProps
            ? commerceProviderComponentProps.saleorApiUrl!
            : "https://vercel.saleor.cloud/graphql/"
        }
      >
        {children}
      </CommerceProviderComponent2>
    </CommerceProviderComponent>
  );
}
