// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7tSQdxgu7FmCVtUmJP9sF2
// Component: QcIugl9q9yRE

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { ProductPriceComponent } from "@plasmicpkgs/commerce";
import Jh from "../../Jh"; // plasmic-import: ABOb0OULcLz3/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 7tSQdxgu7FmCVtUmJP9sF2/projectcss
import sty from "./PlasmicGg.module.css"; // plasmic-import: QcIugl9q9yRE/css

createPlasmicElementProxy;

export type PlasmicGg__VariantMembers = {};
export type PlasmicGg__VariantsArgs = {};
type VariantPropType = keyof PlasmicGg__VariantsArgs;
export const PlasmicGg__VariantProps = new Array<VariantPropType>();

export type PlasmicGg__ArgsType = {};
type ArgPropType = keyof PlasmicGg__ArgsType;
export const PlasmicGg__ArgProps = new Array<ArgPropType>();

export type PlasmicGg__OverridesType = {
  root?: Flex__<"div">;
  productPrice?: Flex__<typeof ProductPriceComponent>;
  jh?: Flex__<typeof Jh>;
};

export interface DefaultGgProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicGg__RenderFunc(props: {
  variants: PlasmicGg__VariantsArgs;
  args: PlasmicGg__ArgsType;
  overrides: PlasmicGg__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <ProductPriceComponent
        data-plasmic-name={"productPrice"}
        data-plasmic-override={overrides.productPrice}
        className={classNames("__wab_instance", sty.productPrice)}
      />

      <Jh
        data-plasmic-name={"jh"}
        data-plasmic-override={overrides.jh}
        className={classNames("__wab_instance", sty.jh)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "productPrice", "jh"],
  productPrice: ["productPrice"],
  jh: ["jh"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  productPrice: typeof ProductPriceComponent;
  jh: typeof Jh;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicGg__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicGg__VariantsArgs;
    args?: PlasmicGg__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicGg__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicGg__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicGg__ArgProps,
          internalVariantPropNames: PlasmicGg__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicGg__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGg";
  } else {
    func.displayName = `PlasmicGg.${nodeName}`;
  }
  return func;
}

export const PlasmicGg = Object.assign(
  // Top-level PlasmicGg renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    productPrice: makeNodeComponent("productPrice"),
    jh: makeNodeComponent("jh"),

    // Metadata about props expected for PlasmicGg
    internalVariantProps: PlasmicGg__VariantProps,
    internalArgProps: PlasmicGg__ArgProps
  }
);

export default PlasmicGg;
/* prettier-ignore-end */
