// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: inZbT2cb4Q4N9HnsiChzn4

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { CommerceProviderComponent } from "@plasmicpkgs/commerce-saleor";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  commerceProviderComponentProps?: Partial<
    Omit<React.ComponentProps<typeof CommerceProviderComponent>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, commerceProviderComponentProps } = props;

  return (
    <CommerceProviderComponent
      {...commerceProviderComponentProps}
      saleorApiUrl={
        commerceProviderComponentProps &&
        "saleorApiUrl" in commerceProviderComponentProps
          ? commerceProviderComponentProps.saleorApiUrl!
          : "https://vercel.saleor.cloud/graphql/"
      }
    >
      {children}
    </CommerceProviderComponent>
  );
}
